// ----------------------------------------------------------------------
// -- INTERACTIVE SETTINGS:
// ----------------------------------------------------------------------
// -- NOTE: Do not edit this file unless you are a WDS team member.
// -- ABOUT: This file is the configuration of the interactive, and the starting code.
// -- Authors/Assembler: jmullins@flvs.net
// ======================================================================


// ----------------------------------------------------------------------
// -- IL SETTINGS
// ----------------------------------------------------------------------	
var il_location = "live"; // live, local
var core_folder = ''; // From Root - IF SET to Local this is where the core files should be
var il_Version = 'il_3.5';

// ----------------------------------------------------------------------
// -- INCLUDED FILES
// ----------------------------------------------------------------------
// -- String Array
// -- example: 'css/csslibs.css','js/jslibs.js'
// ----------------------------------------------------------------------
var incl_css = ['css/02_01_03.css'];
var incl_js = ['js/02_01_03.js'];

// ----------------------------------------------------------------------
// -- GENERAL SETTINGS
// ----------------------------------------------------------------------
var il_settings = {}; // do not edit

// Icluded js libraries
il_settings['jQueryUI'] = true; // true / false
il_settings['jQMath'] = false; // true / false
il_settings['mediaElements'] = true; // true / false

// Look & Feel
il_settings['uiSkin'] = '../../../../global/css/ilskin/template/ui_interactive_skin_template.css'; //jQueryUI CSS file
il_settings['meSkin'] = ''; //MediaElements CSS file

// Goggle Analytics
il_settings['use_analytics'] = false;
il_settings['ua_account'] = ''; // your dedicated GoogleUA account number


// ----------------------------------------------------------------------
// -- DO NOT EDIT BELOW THIS LINE
// ----------------------------------------------------------------------


var il_cdn_location = "http://cdn.flvs.net/cdn/il/"+ il_Version ;

// FLVS Global Object
var ilVar = {
		il_settings:il_settings,
		ui_options : ''
	}; 

//-------- these are to find all js, css files in other core files ---------//
var url_from_page = (il_location == 'local') ? core_folder : il_cdn_location; 

//-------- these are specifically to pull in require.js -------//
//-------- do not edit, unless you are FW team ----------------//
var imported = document.createElement('script');
var att = document.createAttribute("data-main");

imported.src = url_from_page+'/scripts/require.js';
att.value = url_from_page+'/scripts/start.js';

document.head.appendChild(imported).setAttributeNode(att);

//-------Hide Flickr of Static Content---------//
var initCSS = document.createElement('style');
initCSS.type = 'text/css';
initCSS.media = 'screen';
document.getElementsByTagName("head")[0].appendChild(initCSS);
initCSS.appendChild(document.createTextNode("body{visibility:hidden;}")); 

